### ISSUE TITLE
Frontend bauen, von welchem die Gatling Tests gestartet werden können

### ISSUE THREAD

**Issue by krisschaaf** [Ivan-Bobrov/Make-Spring-PetClinic-Microservices-Crash#36]

**Comment by sckoenig** [comment]
- konfigurierte Lasttests sollen ausgeführt werden können.
- soll auf einer VM laufen und von außen ausführbar sein.
- Soll auf einer anderen VM laufen als die Application
- Szenario auswählen:
    - Aufwärmphase, z.B. Loading Screen
    - Richtiger Lasttest
    - Ergebnisse müssen irgendwie zurückgegeben werden
        - Gatling speichert Ergebnisse in einer html datei und zeigt den Link dazu in der Konsole an, wenn der Test vorbei ist.
