### ISSUE TITLE
eigenes Config-Repo erstellen

### ISSUE THREAD

**Issue by rebexo** [Ivan-Bobrov/Make-Spring-PetClinic-Microservices-Crash#7]
- das der Config Server lädt versionierte Config-Daten aus einem hinterlegten Repo, dieses wäre neu zu erstellen mit gewünschten Konfigurationen

**Comment by Lon3035** [comment]
Fork from: https://github.com/spring-petclinic/spring-petclinic-microservices-config

**Comment by Lon3035** [comment]
https://github.com/Lon3035/make-spring-petclinic-microservices-config-crash
